import type { Phase } from "./types";

export const PHASES: Phase[] = [
  {
    id: "rtl",
    label: "RTL",
    title: "Scrivi e simula RTL",
    action: "rtl_sim",
    hint: "Verilog · Icarus",
    help: "Modifica il design Verilog, salva automaticamente, poi lancia la simulazione comportamentale. Valida la logica prima di ogni passo fisico.",
    tool: "Icarus Verilog",
    icon: "code",
    estTime: "~5 s",
  },
  {
    id: "synth",
    label: "Sintesi",
    title: "Sintesi logica",
    action: "synth",
    hint: "Yosys · ABC",
    help: "Trasforma RTL in netlist e database fisico iniziale. Scegli vincoli SDC e modalità ABC area/delay.",
    tool: "Yosys + OpenROAD",
    icon: "cpu",
    estTime: "~30 s",
  },
  {
    id: "floorplan",
    label: "Floorplan",
    title: "Floorplan e die",
    action: "floorplan",
    hint: "Die · IO · tap",
    help: "Definisce il die, i margini IO e genera la PDN (pdngen). L'utilizzo del core influenza l'area finale del chip.",
    tool: "OpenROAD init_floorplan + pdngen",
    icon: "grid",
    estTime: "~20 s",
  },
  {
    id: "pdn",
    label: "PDN",
    title: "Analisi chip PDN",
    action: "gridcheck",
    hint: "check_power_grid",
    help: "Verifica connettività VDD/VSS (PSM-0040). Dopo finish: chip IR opzionale su mesh SPICE (write_pg_spice). Vedi catena power.",
    tool: "OpenROAD check_power_grid",
    icon: "zap",
    estTime: "~5 s",
  },
  {
    id: "place",
    label: "Place",
    title: "Placement",
    action: "place",
    hint: "GP · DP",
    help: "Global e detailed placement delle celle standard. La densità addon regola lo spazio libero tra le righe.",
    tool: "OpenROAD global/detail place",
    icon: "box",
    estTime: "~45 s",
  },
  {
    id: "cts",
    label: "CTS",
    title: "Clock tree synthesis",
    action: "cts",
    hint: "Skew · TNS",
    help: "Costruisce l'albero di clock e ripara timing post-placement. Può richiedere diversi minuti.",
    tool: "OpenROAD CTS + repair",
    icon: "branch",
    estTime: "2–5 min",
  },
  {
    id: "route",
    label: "Route",
    title: "Routing",
    action: "route",
    hint: "Global · Detail",
    help: "Instrada i segnali sui layer metal. Fase più lunga del flusso — conferma prima di avviare.",
    tool: "OpenROAD global/detail route",
    icon: "route",
    estTime: "3–8 min",
  },
  {
    id: "finish",
    label: "GDSII",
    title: "Finish e signoff",
    action: "finish",
    hint: "GDS · SPEF",
    help: "Genera GDSII, SPEF, netlist finale e report. Apri KLayout o la GUI OpenROAD sui risultati.",
    tool: "OpenROAD finish + KLayout",
    icon: "layers",
    estTime: "1–3 min",
  },
  {
    id: "pkg",
    label: "PKG",
    title: "Package · System PDN",
    action: "system_pdn",
    hint: "VRM → board → pkg → die",
    help: "System PDN ngspice: Z(f) e load-step VRM→board→pkg→die. Usa I_die da activity_power. Catena completa: power_chain.",
    tool: "ngspice · system_pdn_hier",
    icon: "package",
    estTime: "~5 s",
  },
];

export const PHASE_IDS = PHASES.map((p) => p.id);
import { LONG_ACTIONS } from "@/lib/actions";

export { LONG_ACTIONS };
export const ANALYSIS_PHASES = new Set(["pdn", "pkg"]);
